## <strong> 12. 결측 데이터 처리

In [1]:
# 필요한 라이브러리
import pandas as pd
import numpy as np

#### <strong> 결측치의 표현: None 객체

In [4]:
# None 객체를 포함한 배열
arr1 = np.array([1, 2, None, 4])
print(arr1.dtype)

# 결측치가 없는 배열
arr2 = np.array([1, 2, 3, 4])
print(arr2.dtype)

object
int32

In [5]:
# Object 객체는 numpy, pandas 연산과 호환되지 않음
arr1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

#### <strong> 결측치의 표현: NaN 값

In [6]:
# NaN 값을 포함한 배열 객체
arr3 = np.array([1, np.nan, 3, 4])
arr3.dtype

dtype('float64')

In [7]:
# NaN 값에 대한 산술 연산
print(1 + np.nan)
print(0 * np.nan)
print(arr3.sum())

nan
nan
nan

In [8]:
# NaN값을 무시하는 집계함수(numpy)
print(np.nansum(arr3))
print(np.nanmax(arr3))
print(np.nanmin(arr3))

8.0
4.0
1.0

In [9]:
# Pandas는 None 객체를 자동으로 NaN값으로 변환한다.

ser = pd.Series([1, np.nan, 2, None])
print(ser)

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

### <strong> Pandas를 이용한 결측치 처리
---

#### <strong>마스킹을 통한 Null 값 표현
+ ```isnull()```
+ ```notnull()```

In [10]:
# [+] 결측치를 포함한 Series 객체 생성
ser = pd.Series([1, np.nan, 2, None])

In [11]:
# [+] isnull()
ser.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [13]:
# [+] notnull()
ser.notnull()

0     True
1    False
2     True
3    False
dtype: bool

#### <strong> 결측치를 포함한 행 또는 열 삭제
+ dropna()

In [14]:
# DataFrame 생성 함수
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind]
           for c in cols}

    return pd.DataFrame(data, ind)

df = make_df('ABC', [0, 1, 2])
df

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [16]:
# [+] NaN 값 추가
df.iloc[0,1] = np.nan
df.iloc[2,1] = np.nan
df

    A    B   C
0  A0  NaN  C0
1  A1   B1  C1
2  A2  NaN  C2

In [17]:
# [+] 결측치를 포함한 행 삭제
df.dropna(axis=0)

    A   B   C
1  A1  B1  C1

In [18]:
# [+] 결측치를 포함한 열 삭제
df.dropna(axis=1)

    A   C
0  A0  C0
1  A1  C1
2  A2  C2

In [32]:
# [+] NaN 값 추가 (C컬럼 전체를 결측지로 변경)
df['C'] = np.nan
df

,CO(GT),PT08.S1(CO),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),RH,AH,C6H6(GT),C
Datetime,,,,,,,,,,,,
2004-03-10 18:00:00,2.6,1360.0,1046.0,166.0,1056.0,113.0,1692.0,1268.0,48.9,0.7578,11.9,NaN
2004-03-10 19:00:00,2.0,1292.0,955.0,103.0,1174.0,92.0,1559.0,972.0,47.7,0.7255,9.4,NaN
2004-03-10 20:00:00,2.2,1402.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,54.0,0.7502,9.0,NaN
2004-03-10 21:00:00,2.2,1376.0,948.0,172.0,1092.0,122.0,1584.0,1203.0,60.0,0.7867,9.2,NaN
2004-03-10 22:00:00,1.6,1272.0,836.0,131.0,1205.0,116.0,1490.0,1110.0,59.6,0.7888,6.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2005-04-04 10:00:00,3.1,1314.0,1101.0,472.0,539.0,190.0,1374.0,1729.0,29.3,0.7568,13.5,NaN
2005-04-04 11:00:00,2.4,1163.0,1027.0,353.0,604.0,179.0,1264.0,1269.0,23.7,0.7119,11.4,NaN
2005-04-04 12:00:00,2.4,1142.0,1063.0,293.0,603.0,175.0,1241.0,1092.0,18.3,0.6406,12.4,NaN
2005-04-04 13:00:00,2.1,1003.0,961.0,235.0,702.0,156.0,1041.0,770.0,13.5,0.5139,9.5,NaN
2005-04-04 14:00:00,2.2,1071.0,1047.0,265.0,654.0,168.0,1129.0,816.0,13.1,0.5028,11.9,NaN

In [20]:
# [+] NaN값이 한 개라도 포함되면 행 또는 열 삭제
df.dropna(axis=0, how='any')

    A   B   C
1  A1  B1  C1

In [21]:
# [+] 모든 값이 전부 NaN값인 행 또는 열 삭제
df.dropna(axis=1, how='all')

    A    B   C
0  A0  NaN  C0
1  A1   B1  C1
2  A2  NaN  C2

In [ ]:
# [+] Non-null(정상으로 측정된) 값의 개수가 임계치보다 작은 행을 삭제
df.dropna(axis=0, thresh=2)

In [22]:
# [+] Non-null 값의 개수가 임계치보다 작은 열을 삭제
df.dropna(axis=1, thresh=2)

    A   C
0  A0  C0
1  A1  C1
2  A2  C2

#### <strong> NaN값을 다른 값을 대체
+ ```fillna()```

In [ ]:
# Series 객체 생성
ser = pd.Series([1, np.nan, 2, None, 3],
                index=list('abcde'))
ser

In [25]:
# [+] 결측치를 특정 값을 대체
df.fillna(0)

    A   B   C
0  A0   0  C0
1  A1  B1  C1
2  A2   0  C2

In [28]:
# [+] Forward-fill 방식(= LOCF)
ser.ffill().fillna(method='bfill')

C:\Users\wmitt\AppData\Local\Temp\ipykernel_3420\3838349247.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ser.ffill().fillna(method='bfill')

0    1.0
1    1.0
2    2.0
3    2.0
dtype: float64

In [29]:
# [+] Backward-fill 방식(= NOCB)
ser.bfill().fillna(method='ffill')

C:\Users\wmitt\AppData\Local\Temp\ipykernel_3420\2582855827.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ser.bfill().fillna(method='ffill')

0    1.0
1    2.0
2    2.0
3    2.0
dtype: float64

### <strong> 결측치 처리 예제: Air Quality 데이터셋

In [30]:
from datetime import datetime
from matplotlib import pyplot as plt

"""
Load AirQualityUCI Data
"""

def parser(x):
    return datetime.strptime(x, '%Y-%m-%d %H:%M:%S')

input_file = './data/AirQualityUCI_refined.csv'

df = pd.read_csv(input_file,
                 index_col=[0],
                 parse_dates=[0],
                 date_parser=parser)

C:\Users\wmitt\AppData\Local\Temp\ipykernel_3420\1865652950.py:13: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(input_file,

In [33]:
# 데이터 요약
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9357 entries, 2004-03-10 18:00:00 to 2005-04-04 14:00:00
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CO(GT)         7765 non-null   float64
 1   PT08.S1(CO)    8991 non-null   float64
 2   PT08.S2(NMHC)  8991 non-null   float64
 3   NOx(GT)        7718 non-null   float64
 4   PT08.S3(NOx)   8991 non-null   float64
 5   NO2(GT)        7715 non-null   float64
 6   PT08.S4(NO2)   8991 non-null   float64
 7   PT08.S5(O3)    8991 non-null   float64
 8   RH             8991 non-null   float64
 9   AH             8991 non-null   float64
 10  C6H6(GT)       9357 non-null   float64
 11  C              0 non-null      float64
dtypes: float64(12)
memory usage: 950.3 KB

In [34]:
# 시각화 설정 옵션
%matplotlib qt5
%config InlineBackend.figure_format = 'svg'

plt.rcParams['figure.figsize'] = [12, 5]
plt.rcParams['font.size'] = 13
plt.ion()

In [35]:
# 결측 데이터 시각화
import missingno

missingno.matrix(df)

In [36]:
# 일산화탄소(CO) 시계열 시각화
df['CO(GT)'].plot()

In [ ]:
# 결측치 대치
imp_locf = df['CO(GT)'].copy().ffill() # LOCF
imp_nocb = df['CO(GT)'].copy().bfill() # NOCB
imp_linear = df['CO(GT)'].copy().interpolate() # 선형 보간
imp_mean = df['CO(GT)'].copy().fillna(df['CO(GT)'].mean())  # 평균값 대체

In [ ]:
# K-NN 대치
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=2)    # default: 2
imp_knn = df.copy().values
imp_knn = imputer.fit_transform(imp_knn)

In [ ]:
# K-NN 대치 결과 변환(ndarray -> DataFrame)
imp_df = pd.DataFrame(imp_knn, index=imp_locf.index, columns=df.columns)

In [ ]:
# 결측치 처리 결과 시각화
plt.plot(df['CO(GT)'], label='actual', zorder=10)
plt.plot(imp_linear, label='linear interpolation', zorder=3)
plt.plot(imp_nocb, label='nocb', zorder=2)
plt.plot(imp_locf, label='locf', zorder=1)
plt.plot(imp_mean, label='mean substitution', zorder=4)
plt.plot(imp_df['CO(GT)'], label='k-nearest neighbor', zorder=5)
plt.legend(loc='best')
plt.show()